---
name: terraform-prod
"on":
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compute plan digest
        run: echo "PLAN_DIGEST=sha256:deadbeef" >> $GITHUB_ENV

      - name: Relia authorize for prod apply
        uses: ./.github/actions/relia-authorize
        with:
          relia_url: ${{ secrets.RELIA_URL }}
          action: terraform.apply
          resource: aws:account:123456789012:stack/prod
          env: prod
          intent_json: >
            {"change_id":"CHG-1234","ticket":"JIRA-555","reason":"Apply approved infra change"}
          plan_digest: ${{ env.PLAN_DIGEST }}
          diff_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Terraform apply (now has short-lived creds)
        run: |
          terraform init
          terraform apply -auto-approve
